name: Benchmark

on:
  push:

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        zod:
          - zod-4@npm:zod@4.0.16
          - zod-3@npm:zod@3.25.76
          - zod-3@npm:zod@3.2.0
          - zod-3@npm:myzod@1.12.1
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm add ${{ matrix.zod }}

      - run: pnpm run benchmark | tee output.txt
        env:


      - run: |
          echo "### ${{ matrix.zod}}" >> $GITHUB_STEP_SUMMARY
          echo "`\`\`\" >> $GITHUB_STEP_SUMMARY
          cat output.txt >> $GITHUB_STEP_SUMMARY
          echo "`\`\`\" >> $GITHUB_STEP_SUMMARY
