name: Benchmark

on:
  push:

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        zod:
          - npm:zod
          - npm:zod@3.2.0
          - npm:myzod
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm add zod@${{ matrix.zod }}

      - run: pnpm run benchmark | tee output.txt

      - run: |
          echo "### ${{ matrix.zod}}" >> $GITHUB_STEP_SUMMARY
          echo "`\`\`\" >> $GITHUB_STEP_SUMMARY
          cat output.txt >> $GITHUB_STEP_SUMMARY
          echo "`\`\`\" >> $GITHUB_STEP_SUMMARY
